apiVersion: v1
kind: Secret
metadata:
  name: dns-provider-credentials
  namespace: cert-manager
type: Opaque
stringData:
  access-key-id: "${AWS_ACCESS_KEY_ID}"
  secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-provider-credentials
  namespace: external-dns
type: Opaque
stringData:
  access-key-id: "${AWS_ACCESS_KEY_ID}"
  secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
