apiVersion: v1
kind: Secret
metadata:
  name: backup-s3-credentials
  namespace: vault
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${backup_s3_access_key}
  AWS_SECRET_ACCESS_KEY: ${backup_s3_secret_key}
