apiVersion: v1
kind: Secret
metadata:
  name: dns-provider-credentials
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "${cloudflare_api_token}"
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-provider-credentials
  namespace: external-dns
type: Opaque
stringData:
  api-token: "${cloudflare_api_token}"
