# Makefile — Mojaloop deployment toolkit
#
# Two Terraform stacks per environment:
#   src/infra   — cluster VMs/managed k8s + Flux bootstrap (slow, infra blast radius)
#   src/config  — cluster-config/secrets, Kustomizations, values overrides
#                 (seconds, cannot touch VMs; Flux converges on next cycle)
#
# Usage:
#   make plan-apply ENV=<env>     # Full deployment (infra then config)
#   make apply-config ENV=<env>   # Push config changes only (fast path)
#   make validate ENV=<env>       # Schema + terraform validation
#   make secrets ENV=<env>        # Show generated internal passwords

SHELL := /bin/bash
ENV ?=
ENV_DIR := environments/$(ENV)
ENV_FILE := $(ENV_DIR)/.env
ARTIFACTS_DIR := artifacts/$(ENV)/terraform
INFRA_DIR := src/infra
CONFIG_DIR := src/config
INFRA_PLAN := $(ARTIFACTS_DIR)/tfplan-infra
CONFIG_PLAN := $(ARTIFACTS_DIR)/tfplan-config
INFRA_BACKEND := path=../../artifacts/$(ENV)/terraform/infra.tfstate
CONFIG_BACKEND := path=../../artifacts/$(ENV)/terraform/config.tfstate

# External credential names read from .env into the TF_VAR_secrets map.
# UPPER_CASE password names double as generation overrides (migrating envs /
# external-unmanaged data stores).
SECRET_KEYS := \
	DIGITALOCEAN_TOKEN CLOUDFLARE_API_TOKEN \
	AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION \
	POWERDNS_API_URL POWERDNS_API_KEY \
	OCI_REPO_USERNAME OCI_REPO_PASSWORD \
	OCI_PROXY_USERNAME OCI_PROXY_PASSWORD \
	SMTP_USER SMTP_PASSWORD TELEGRAM_BOT_TOKEN \
	BACKUP_S3_ACCESS_KEY BACKUP_S3_SECRET_KEY \
	MINIO_ROOT_USER MINIO_ROOT_PASSWORD HARBOR_ADMIN_PASSWORD GRAFANA_ADMIN_PASSWORD \
	MYSQL_ROOT_PASSWORD MYSQL_CENTRAL_LEDGER_PASSWORD MYSQL_ACCOUNT_LOOKUP_PASSWORD \
	MYSQL_ORACLE_MSISDN_PASSWORD MONGODB_ROOT_PASSWORD MONGODB_APP_PASSWORD \
	KRATOS_DB_PASSWORD KETO_DB_PASSWORD HYDRA_DB_PASSWORD MCM_DB_PASSWORD \
	HUB_ADMIN_PASSWORD MCM_OIDC_CLIENT_SECRET ROLE_ASSIGN_SVC_SECRET \
	KRATOS_SECRETS_CIPHER KRATOS_SECRETS_COOKIE KRATOS_SECRETS_CSRF_COOKIE \
	KRATOS_SECRETS_DEFAULT HYDRA_SECRETS_SYSTEM HYDRA_SECRETS_COOKIE

# Load .env, then build TF_VAR_secrets with jq (reads the process environment
# directly — no shell interpolation of secret values, quote-safe by design).
LOAD_ENV = set -a && source ../../$(ENV_FILE) && set +a && \
	export TF_VAR_env_name=$(ENV) && \
	export TF_SECRET_KEYS="$(strip $(SECRET_KEYS))" && \
	export TF_VAR_secrets=$$(jq -cn 'env.TF_SECRET_KEYS | split(" ") | map({key: ., value: (env[.] // "")}) | from_entries') && \
	export AWS_ACCESS_KEY_ID=$${AWS_ACCESS_KEY_ID:-unused} \
	       AWS_SECRET_ACCESS_KEY=$${AWS_SECRET_ACCESS_KEY:-unused}

# Placeholder kubeconfig — the alekc/kubectl provider validates (stats + loads)
# its config_path at plan time, before the real kubeconfig exists on fresh
# deploys. The placeholder content is never dialed: the infra stack rewrites
# the file during apply before any kubernetes/kubectl provider is configured.
KUBECONFIG_FILE := artifacts/$(ENV)/kubernetes/kubeconfig
define ENSURE_KUBECONFIG
	mkdir -p artifacts/$(ENV)/kubernetes; \
	if [ ! -f "$(KUBECONFIG_FILE)" ]; then \
		printf '%s\n' \
			'# Placeholder generated by make — overwritten by terraform apply' \
			'apiVersion: v1' \
			'kind: Config' \
			'clusters:' \
			'- cluster:' \
			'    server: https://127.0.0.1:1' \
			'  name: pending' \
			'contexts:' \
			'- context: {cluster: pending, user: pending}' \
			'  name: pending' \
			'current-context: pending' \
			'users:' \
			'- name: pending' \
			'  user: {token: pending}' \
			> "$(KUBECONFIG_FILE)"; \
		echo "Seeded placeholder kubeconfig at $(KUBECONFIG_FILE)"; \
	fi
endef

define CHECK_ENV
	@if [ -z "$(ENV)" ]; then echo "ERROR: ENV is required, e.g. make $@ ENV=my-env"; exit 1; fi
	@if [ ! -f "$(ENV_DIR)/config.yaml" ]; then echo "ERROR: $(ENV_DIR)/config.yaml not found"; exit 1; fi
endef

# Both stack directories are shared by every environment, and terraform silently
# reuses whichever backend was last initialized there. Any target that runs
# terraform MUST rebind the backend to $(ENV) first — otherwise `make destroy
# ENV=a` happily operates on environment b's state, reporting success.
# -reconfigure (not -upgrade) keeps this cheap enough to do every time.
BIND_INFRA  = terraform init -reconfigure -input=false -backend-config="$(INFRA_BACKEND)" >/dev/null
BIND_CONFIG = terraform init -reconfigure -input=false -backend-config="$(CONFIG_BACKEND)" >/dev/null

.DEFAULT_GOAL := help

# GitOps artifact settings (override via env or command line)
GITOPS_DIR := gitops
OCI_REPO = $(shell yq -r '.artifact.url' $(ENV_DIR)/config.yaml 2>/dev/null | sed 's|^oci://||')
GITOPS_VERSION ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo "latest")

.PHONY: help init init-infra init-config validate fmt plan plan-infra plan-config \
	apply apply-infra apply-config plan-apply destroy destroy-fast clean secrets \
	list show render render-thanos render-cilium push-gitops tag-gitops list-artifacts release

help:
	@echo "Available targets (all need ENV=<name>, reading environments/<name>/):"
	@echo ""
	@echo "Main commands:"
	@echo "  make validate      - Schema-validate config.yaml + template, terraform validate"
	@echo "  make plan-apply    - Full deployment: infra stack, then config stack"
	@echo "  make apply-config  - Fast path: apply ONLY config changes (no infra plan)"
	@echo "  make secrets       - Show generated internal service passwords"
	@echo ""
	@echo "Stack-level commands:"
	@echo "  make init | plan | apply           - Both stacks in order"
	@echo "  make plan-infra | apply-infra      - Infra stack only"
	@echo "  make plan-config                   - Config stack only"
	@echo ""
	@echo "Destroy:"
	@echo "  make destroy       - Destroy config then infra stack"
	@echo "  make destroy-fast  - Destroy without refresh (resources already gone)"
	@echo ""
	@echo "GitOps artifact:"
	@echo "  make push-gitops [GITOPS_VERSION=v1.0.0]  - Push gitops/ as OCI artifact"
	@echo "  make tag-gitops TAG=latest                - Tag an existing artifact"
	@echo "  make release TAG=v0.3.0                   - Git tag + OCI artifact push"
	@echo "  make list-artifacts                       - List published versions"
	@echo ""
	@echo "Rendering: make render | render-thanos | render-cilium"
	@echo "Utilities: make fmt | clean | list | show"

# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------

validate:
	$(CHECK_ENV)
	@echo "Validating $(ENV_DIR)/config.yaml against schema..."
	@yq -o json e '.' $(ENV_DIR)/config.yaml | python3 tools/validate.py config/schemas/environment.schema.json
	@role=$$(yq -r '.cluster.role' $(ENV_DIR)/config.yaml); \
	 tmpl=$$(yq -r '.template' $(ENV_DIR)/config.yaml); \
	 tfile="config/templates/$$role/$$tmpl.yaml"; \
	 if [ ! -f "$$tfile" ]; then echo "ERROR: template $$tfile not found"; exit 1; fi; \
	 echo "Validating $$tfile against schema..."; \
	 yq -o json e '.' "$$tfile" | python3 tools/validate.py config/schemas/template.schema.json
	@provider=$$(yq -r '.infra.provider' $(ENV_DIR)/config.yaml); \
	 mfile="config/templates/mappings/$$provider.yaml"; \
	 if [ ! -f "$$mfile" ]; then echo "ERROR: provider mapping $$mfile not found"; exit 1; fi; \
	 yq -o json e '.' "$$mfile" | python3 tools/validate.py config/schemas/mapping.schema.json
	@if [ -d "$(INFRA_DIR)/.terraform" ]; then \
		cd $(INFRA_DIR) && $(LOAD_ENV) && terraform validate && cd ../../$(CONFIG_DIR) && $(LOAD_ENV) && terraform validate; \
	else \
		echo "(terraform validate skipped — run 'make init ENV=$(ENV)' first for full validation)"; \
	fi
	@echo "Validation OK"

fmt:
	@cd src && terraform fmt -recursive

# --------------------------------------------------------------------------
# Init / Plan / Apply
# --------------------------------------------------------------------------

init-infra:
	$(CHECK_ENV)
	@mkdir -p $(ARTIFACTS_DIR)
	@$(ENSURE_KUBECONFIG)
	@cd $(INFRA_DIR) && $(LOAD_ENV) && terraform init -upgrade -reconfigure \
		-backend-config="$(INFRA_BACKEND)"

init-config:
	$(CHECK_ENV)
	@mkdir -p $(ARTIFACTS_DIR)
	@$(ENSURE_KUBECONFIG)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && terraform init -upgrade -reconfigure \
		-backend-config="$(CONFIG_BACKEND)"

init: init-infra init-config

plan-infra: init-infra
	$(CHECK_ENV)
	@echo "Planning infra stack (ENV=$(ENV))..."
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform plan -out=../../$(INFRA_PLAN)

plan-config: init-config
	$(CHECK_ENV)
	@echo "Planning config stack (ENV=$(ENV))..."
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform plan -out=../../$(CONFIG_PLAN)

plan: plan-infra plan-config

apply-infra:
	$(CHECK_ENV)
	@if [ ! -f "$(INFRA_PLAN)" ]; then echo "No infra plan — run 'make plan-infra ENV=$(ENV)'"; exit 1; fi
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform apply ../../$(INFRA_PLAN)

# Fast path: config changes converge without touching infrastructure.
apply-config: init-config
	$(CHECK_ENV)
	@echo "Applying config stack only (ENV=$(ENV))..."
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform plan -out=../../$(CONFIG_PLAN)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform apply ../../$(CONFIG_PLAN)

apply:
	$(CHECK_ENV)
	@if [ ! -f "$(INFRA_PLAN)" ]; then echo "No infra plan — run 'make plan ENV=$(ENV)'"; exit 1; fi
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform apply ../../$(INFRA_PLAN)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform plan -out=../../$(CONFIG_PLAN)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform apply ../../$(CONFIG_PLAN)

# Plan and apply both stacks in order (config planned AFTER infra applies, so
# it sees the real cluster).
plan-apply: init
	$(CHECK_ENV)
	@echo "Deploying infra stack (ENV=$(ENV))..."
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform plan -out=../../$(INFRA_PLAN)
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform apply ../../$(INFRA_PLAN)
	@echo "Deploying config stack (ENV=$(ENV))..."
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform plan -out=../../$(CONFIG_PLAN)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform apply ../../$(CONFIG_PLAN)

# --------------------------------------------------------------------------
# Generated secrets
# --------------------------------------------------------------------------

secrets:
	$(CHECK_ENV)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform output -json generated_secrets | jq .

# --------------------------------------------------------------------------
# Destroy
# --------------------------------------------------------------------------

destroy:
	$(CHECK_ENV)
	@echo "WARNING: destroying ALL infrastructure for ENV=$(ENV)!"
	@echo "Press Ctrl+C to cancel, or wait 5 seconds to continue..."
	@sleep 5
	@$(ENSURE_KUBECONFIG)
	@echo "Destroying config stack (best effort)..."
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform destroy -auto-approve -refresh=false || true
	@echo "Destroying infra stack..."
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform destroy -auto-approve

destroy-fast:
	$(CHECK_ENV)
	@echo "WARNING: fast destroy without refresh (ENV=$(ENV))!"
	@echo "Press Ctrl+C to cancel, or wait 3 seconds to continue..."
	@sleep 3
	@$(ENSURE_KUBECONFIG)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform destroy -auto-approve -refresh=false || true
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform destroy -auto-approve -refresh=false

# Removes generated artifacts for ONE environment, never the Terraform state —
# deleting state orphans running VMs and managed clusters.
clean:
	$(CHECK_ENV)
	@echo "Removing generated artifacts for $(ENV) (state is preserved)..."
	@rm -rf artifacts/$(ENV)/kubernetes artifacts/$(ENV)/talos artifacts/$(ENV)/talos-config \
		artifacts/$(ENV)/talos-secrets $(INFRA_PLAN) $(CONFIG_PLAN)
	@echo "Done. Terraform state under artifacts/$(ENV)/terraform/ was kept."

list:
	$(CHECK_ENV)
	@echo "--- infra stack ---"
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform state list
	@echo "--- config stack ---"
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform state list

show:
	$(CHECK_ENV)
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform show

# --------------------------------------------------------------------------
# Manifest Rendering (Jsonnet -> YAML)
# --------------------------------------------------------------------------

CILIUM_VERSION ?= 1.20.0
CILIUM_MANIFEST := config/manifests/cilium-$(CILIUM_VERSION).yaml

render: render-thanos render-cilium

render-thanos:
	@echo "Rendering Thanos manifests..."
	@cd rendering/thanos && jb install && \
	jsonnet -J vendor -m ../../gitops/tooling-observability/thanos/ thanos.jsonnet && \
	cd ../../gitops/tooling-observability/thanos && \
	for f in thanos-*; do [ -f "$$f" ] && [ "$${f##*.}" != "yaml" ] && yq -p json -o yaml "$$f" > "$$f.yaml" && rm "$$f"; done || true
	@echo "Thanos manifests rendered to gitops/tooling-observability/thanos/"

render-cilium:
	@echo "Rendering Cilium $(CILIUM_VERSION) bootstrap manifest..."
	@mkdir -p config/manifests
	@cat rendering/cilium/namespace.yaml > $(CILIUM_MANIFEST)
	@helm template cilium cilium \
		--repo https://helm.cilium.io/ \
		--version $(CILIUM_VERSION) \
		--namespace cilium \
		-f rendering/cilium/values.yaml \
		>> $(CILIUM_MANIFEST)
	@if grep -q "^kind: Secret" $(CILIUM_MANIFEST); then \
		rm $(CILIUM_MANIFEST); \
		echo "ERROR: rendered manifest contains Secrets — check hubble is disabled"; \
		exit 1; \
	fi
	@echo "Rendered to $(CILIUM_MANIFEST)"

# --------------------------------------------------------------------------
# GitOps OCI Artifact Management
# --------------------------------------------------------------------------

push-gitops:
	$(CHECK_ENV)
	@echo "Pushing gitops artifact to oci://$(OCI_REPO):$(GITOPS_VERSION)..."
	@set -a && source $(ENV_FILE) && set +a && \
	flux push artifact oci://$(OCI_REPO):$(GITOPS_VERSION) \
		--path=./$(GITOPS_DIR) \
		--source="$(shell git config --get remote.origin.url)" \
		--revision="$(shell git rev-parse --short HEAD)" \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD"
	@echo "Pushed oci://$(OCI_REPO):$(GITOPS_VERSION)"

tag-gitops:
	$(CHECK_ENV)
	@if [ -z "$(TAG)" ]; then echo "Usage: make tag-gitops TAG=v1.0.0"; exit 1; fi
	@set -a && source $(ENV_FILE) && set +a && \
	flux tag artifact oci://$(OCI_REPO):$(GITOPS_VERSION) --tag=$(TAG) \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD"
	@echo "Tagged oci://$(OCI_REPO):$(GITOPS_VERSION) as $(TAG)"

release:
	$(CHECK_ENV)
	@if [ -z "$(TAG)" ]; then echo "Usage: make release TAG=v0.3.0 [MSG=\"...\"]"; exit 1; fi
	git tag -a $(TAG) -m "$(or $(MSG),Release $(TAG))"
	git push origin $(TAG)
	@set -a && source $(ENV_FILE) && set +a && \
	flux push artifact oci://$(OCI_REPO):$(TAG) \
		--path=./$(GITOPS_DIR) \
		--source="$(shell git config --get remote.origin.url)" \
		--revision="$(TAG)@sha1:$(shell git rev-parse HEAD)" \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD" && \
	flux tag artifact oci://$(OCI_REPO):$(TAG) --tag=latest \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD"
	@echo "Released $(TAG)"

list-artifacts:
	$(CHECK_ENV)
	@set -a && source $(ENV_FILE) && set +a && \
	flux list artifacts oci://$(OCI_REPO) \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD"
