# Makefile — Mojaloop deployment toolkit
#
# Two Terraform stacks per environment:
#   src/infra   — cluster VMs/managed k8s + Flux bootstrap (slow, infra blast radius)
#   src/config  — cluster-config/secrets, Kustomizations, values overrides
#                 (seconds, cannot touch VMs; Flux converges on next cycle)
#
# Usage:
#   make plan-apply ENV=<env>     # Full deployment (infra then config)
#   make apply-config ENV=<env>   # Push config changes only (fast path)
#   make validate ENV=<env>       # Schema + terraform validation
#   make secrets ENV=<env>        # Show generated internal passwords

SHELL := /bin/bash
ENV ?=
# Adopter data lives OUTSIDE the clone, in sibling directories under the
# project root (see doc/architecture/config-layering-design.md). Both roots are entry-point
# parameters; override them for a non-standard layout, e.g.
#   make plan ENV=x ENVIRONMENTS_ROOT=/path/to/envs ARTIFACTS_ROOT=/path/to/artifacts
ENVIRONMENTS_ROOT ?= ../environments
ARTIFACTS_ROOT ?= ../artifacts
ENV_DIR := $(ENVIRONMENTS_ROOT)/$(ENV)
ENV_FILE := $(ENV_DIR)/.env
# State gets a visible boundary: it is the NON-REGENERABLE, secret-bearing part
# of the artifacts tree — losing it orphans the cluster. Disposable output
# (plans) lives separately so no cleanup step is ever tempted to touch state/.
STATE_DIR := $(ARTIFACTS_ROOT)/$(ENV)/state
PLANS_DIR := $(ARTIFACTS_ROOT)/$(ENV)/plans
INFRA_DIR := src/infra
CONFIG_DIR := src/config
INFRA_PLAN := $(PLANS_DIR)/tfplan-infra
CONFIG_PLAN := $(PLANS_DIR)/tfplan-config
# abspath keeps overrides working whether the roots are given relative (to the
# repo root, where make runs) or absolute; terraform init runs in src/<stack>.
INFRA_BACKEND := path=$(abspath $(STATE_DIR))/infra.tfstate
CONFIG_BACKEND := path=$(abspath $(STATE_DIR))/config.tfstate

# External credential names read from .env into the TF_VAR_secrets map.
# UPPER_CASE password names double as generation overrides (migrating envs /
# external-unmanaged data stores).
SECRET_KEYS := \
	DIGITALOCEAN_TOKEN CLOUDFLARE_API_TOKEN \
	AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION \
	POWERDNS_API_URL POWERDNS_API_KEY \
	ACME_EAB_KEY_ID ACME_EAB_HMAC_ENCODED \
	OCI_REPO_USERNAME OCI_REPO_PASSWORD \
	OCI_PROXY_USERNAME OCI_PROXY_PASSWORD \
	SMTP_USER SMTP_PASSWORD TELEGRAM_BOT_TOKEN \
	BACKUP_S3_ACCESS_KEY BACKUP_S3_SECRET_KEY \
	OBS_INGEST_USERNAME OBS_INGEST_PASSWORD \
	MINIO_ROOT_USER MINIO_ROOT_PASSWORD HARBOR_ADMIN_PASSWORD GRAFANA_ADMIN_PASSWORD \
	MYSQL_ROOT_PASSWORD MYSQL_CENTRAL_LEDGER_PASSWORD MYSQL_ACCOUNT_LOOKUP_PASSWORD \
	MYSQL_ORACLE_MSISDN_PASSWORD MONGODB_ROOT_PASSWORD MONGODB_APP_PASSWORD \
	KRATOS_DB_PASSWORD KETO_DB_PASSWORD HYDRA_DB_PASSWORD MCM_DB_PASSWORD \
	HUB_ADMIN_PASSWORD MCM_OIDC_CLIENT_SECRET ROLE_ASSIGN_SVC_SECRET \
	KRATOS_SECRETS_CIPHER KRATOS_SECRETS_COOKIE KRATOS_SECRETS_CSRF_COOKIE \
	KRATOS_SECRETS_DEFAULT HYDRA_SECRETS_SYSTEM HYDRA_SECRETS_COOKIE

# Load .env, then build TF_VAR_secrets with jq (reads the process environment
# directly — no shell interpolation of secret values, quote-safe by design).
LOAD_ENV = set -a && source $(abspath $(ENV_FILE)) && set +a && \
	export TF_VAR_env_name=$(ENV) && \
	export TF_VAR_environments_dir=$(abspath $(ENVIRONMENTS_ROOT)) && \
	export TF_VAR_artifacts_dir=$(abspath $(ARTIFACTS_ROOT)) && \
	export TF_VAR_dtk_tag=$$(git describe --tags --exact-match 2>/dev/null || true) && \
	export TF_SECRET_KEYS="$(strip $(SECRET_KEYS))" && \
	export TF_VAR_secrets=$$(jq -cn 'env.TF_SECRET_KEYS | split(" ") | map({key: ., value: (env[.] // "")}) | from_entries') && \
	export AWS_ACCESS_KEY_ID=$${AWS_ACCESS_KEY_ID:-unused} \
	       AWS_SECRET_ACCESS_KEY=$${AWS_SECRET_ACCESS_KEY:-unused} \
	       PROXMOX_VE_ENDPOINT=$${PROXMOX_VE_ENDPOINT:-https://unused.invalid:8006} \
	       PROXMOX_VE_API_TOKEN=$${PROXMOX_VE_API_TOKEN:-unused@pam!unused=00000000-0000-0000-0000-000000000000}

# Placeholder kubeconfig — the alekc/kubectl provider validates (stats + loads)
# its config_path at plan time, before the real kubeconfig exists on fresh
# deploys. The placeholder content is never dialed: the infra stack rewrites
# the file during apply before any kubernetes/kubectl provider is configured.
KUBECONFIG_FILE := $(ARTIFACTS_ROOT)/$(ENV)/kubernetes/kubeconfig
define ENSURE_KUBECONFIG
	mkdir -p $(ARTIFACTS_ROOT)/$(ENV)/kubernetes; \
	if [ ! -f "$(KUBECONFIG_FILE)" ]; then \
		printf '%s\n' \
			'# Placeholder generated by make — overwritten by terraform apply' \
			'apiVersion: v1' \
			'kind: Config' \
			'clusters:' \
			'- cluster:' \
			'    server: https://127.0.0.1:1' \
			'  name: pending' \
			'contexts:' \
			'- context: {cluster: pending, user: pending}' \
			'  name: pending' \
			'current-context: pending' \
			'users:' \
			'- name: pending' \
			'  user: {token: pending}' \
			> "$(KUBECONFIG_FILE)"; \
		echo "Seeded placeholder kubeconfig at $(KUBECONFIG_FILE)"; \
	fi
endef

define CHECK_ENV
	@if [ -z "$(ENV)" ]; then echo "ERROR: ENV is required, e.g. make $@ ENV=my-env"; exit 1; fi
	@if [ ! -f "$(ENV_DIR)/config.yaml" ]; then echo "ERROR: $(ENV_DIR)/config.yaml not found"; exit 1; fi
endef

# Both stack directories are shared by every environment, and terraform silently
# reuses whichever backend was last initialized there. Any target that runs
# terraform MUST rebind the backend to $(ENV) first — otherwise `make destroy
# ENV=a` happily operates on environment b's state, reporting success.
# -reconfigure (not -upgrade) keeps this cheap enough to do every time.
BIND_INFRA  = terraform init -reconfigure -input=false -backend-config="$(INFRA_BACKEND)" >/dev/null
BIND_CONFIG = terraform init -reconfigure -input=false -backend-config="$(CONFIG_BACKEND)" >/dev/null

# State files are secret-bearing (Talos machine secrets, credentials in
# resources). Terraform rewrites them 0644 on every apply/destroy — re-tighten
# immediately after. Never fails the target.
PROTECT_STATE = @chmod 700 $(STATE_DIR) 2>/dev/null; chmod 600 $(STATE_DIR)/*.tfstate* 2>/dev/null; true

.DEFAULT_GOAL := help

# GitOps artifact settings (override via env or command line)
GITOPS_DIR := gitops
OCI_REPO = $(shell yq -r '.artifact.url' $(ENV_DIR)/config.yaml 2>/dev/null | sed 's|^oci://||')
GITOPS_VERSION ?= $(shell git rev-parse --short HEAD 2>/dev/null || echo "latest")

.PHONY: help init init-infra init-config validate fmt plan plan-infra plan-config \
	apply apply-infra apply-config plan-apply destroy destroy-fast clean secrets \
	list show render render-thanos render-cilium push-gitops tag-gitops list-artifacts release

help:
	@echo "Available targets (all need ENV=<name>, reading $(ENVIRONMENTS_ROOT)/<name>/):"
	@echo ""
	@echo "Main commands:"
	@echo "  make validate      - Schema-validate config.yaml + template, terraform validate"
	@echo "  make check         - Run all repo contract checks (tools/checks/, no ENV needed)"
	@echo "  make check-pristine [ENV=<env>] - Pristine-clone/tag gate (apply-time)"
	@echo "  make plan-apply    - Full deployment: infra stack, then config stack"
	@echo "  make apply-config  - Fast path: apply ONLY config changes (no infra plan)"
	@echo "  make secrets       - Show generated internal service passwords"
	@echo ""
	@echo "Stack-level commands:"
	@echo "  make init | plan | apply           - Both stacks in order"
	@echo "  make plan-infra | apply-infra      - Infra stack only"
	@echo "  make plan-config                   - Config stack only"
	@echo ""
	@echo "Destroy:"
	@echo "  make destroy       - Destroy config then infra stack"
	@echo "  make destroy-fast  - Destroy without refresh (resources already gone)"
	@echo ""
	@echo "GitOps artifact:"
	@echo "  make push-gitops [GITOPS_VERSION=v1.0.0]  - Push gitops/ as OCI artifact"
	@echo "  make tag-gitops TAG=latest                - Tag an existing artifact"
	@echo "  make release TAG=v0.3.0                   - Git tag + OCI artifact push"
	@echo "  make list-artifacts                       - List published versions"
	@echo ""
	@echo "Performance testing:"
	@echo "  make perf-seed ENV=<env>                   - Register + verify test parties"
	@echo "  make perf-check ENV=<env>                  - Readiness gate (needs kubeconfig)"
	@echo "  make perf-run ENV=<env> SCENARIO=<name>    - Run a load scenario"
	@echo "  make perf-index                            - Regenerate perf/INDEX.md"
	@echo ""
	@echo "Rendering: make render | render-thanos | render-cilium"
	@echo "Utilities: make fmt | clean | list | show"

# --------------------------------------------------------------------------
# Validation
# --------------------------------------------------------------------------

validate:
	$(CHECK_ENV)
	@echo "Validating $(ENV_DIR)/config.yaml against schema..."
	@yq -o json e '.' $(ENV_DIR)/config.yaml | python3 tools/validate.py config/schemas/environment.schema.json
	@role=$$(yq -r '.cluster.role' $(ENV_DIR)/config.yaml); \
	 tmpl=$$(yq -r '.template' $(ENV_DIR)/config.yaml); \
	 provider=$$(yq -r '.infra.provider' $(ENV_DIR)/config.yaml); \
	 tdir="config/templates/$$provider/$$role/$$tmpl"; \
	 if [ ! -d "$$tdir" ]; then echo "ERROR: template directory $$tdir not found"; exit 1; fi; \
	 echo "Validating $$tdir/template.yaml against schema..."; \
	 yq -o json e '.' "$$tdir/template.yaml" | python3 tools/validate.py config/schemas/template.schema.json; \
	 echo "Validating $$tdir/placement.yaml against schema..."; \
	 yq -o json e '.' "$$tdir/placement.yaml" | python3 tools/validate.py config/schemas/template-placement.schema.json
	@provider=$$(yq -r '.infra.provider' $(ENV_DIR)/config.yaml); \
	 pfile="config/templates/$$provider/params.yaml"; \
	 if [ ! -f "$$pfile" ]; then echo "ERROR: provider params $$pfile not found"; exit 1; fi; \
	 echo "Validating $$pfile against schema..."; \
	 yq -o json e '.' "$$pfile" | python3 tools/validate.py config/schemas/params.schema.json
	@if [ -f "$(ENV_DIR)/placement.yaml" ]; then \
	 echo "Validating $(ENV_DIR)/placement.yaml against schema..."; \
	 yq -o json e '.' $(ENV_DIR)/placement.yaml | python3 tools/validate.py config/schemas/placement.schema.json; \
	fi
	@if [ -f "$(ENV_DIR)/proxmox/proxmox.yaml" ]; then \
	 echo "Validating $(ENV_DIR)/proxmox/proxmox.yaml against schema..."; \
	 yq -o json e '.' $(ENV_DIR)/proxmox/proxmox.yaml | python3 tools/validate.py config/schemas/proxmox-env.schema.json; \
	fi
	@if [ -f "$(ENV_DIR)/talos.yaml" ]; then \
	 echo "Validating $(ENV_DIR)/talos.yaml against schema..."; \
	 yq -o json e '.' $(ENV_DIR)/talos.yaml | python3 tools/validate.py config/schemas/talos-env.schema.json; \
	fi
	@if [ -d "$(INFRA_DIR)/.terraform" ]; then \
		cd $(INFRA_DIR) && $(LOAD_ENV) && terraform validate && cd ../../$(CONFIG_DIR) && $(LOAD_ENV) && terraform validate; \
	else \
		echo "(terraform validate skipped — run 'make init ENV=$(ENV)' first for full validation)"; \
	fi
	@echo "Validation OK"

fmt:
	@cd src && terraform fmt -recursive

# --------------------------------------------------------------------------
# Repo contract checks (tools/checks/) — config-layering gates
#
#   make check          - Every repo-state check: substitution token syntax,
#                         HelmRelease valuesFrom chain, P_* provider interface,
#                         secret placement, node-role placement, tool versions,
#                         talos fragments. No ENV required.
#   make check-pristine - Adopter/apply-time gate: clean working tree on an
#                         exact release tag. With ENV=<env>, also verifies the
#                         dtk_version pinned in environments/<env>/config.yaml.
# --------------------------------------------------------------------------
.PHONY: check check-pristine

check:
	@tools/checks/check-all.sh

check-pristine:
	@if [ -n "$(ENV)" ] && [ -f "$(ENV_DIR)/config.yaml" ]; then \
		tools/checks/check-pristine.sh "$(ENV_DIR)/config.yaml"; \
	else \
		tools/checks/check-pristine.sh; \
	fi

# --------------------------------------------------------------------------
# Init / Plan / Apply
# --------------------------------------------------------------------------

init-infra:
	$(CHECK_ENV)
	@mkdir -p $(STATE_DIR) $(PLANS_DIR)
	@chmod 700 $(STATE_DIR)
	@$(ENSURE_KUBECONFIG)
	@cd $(INFRA_DIR) && $(LOAD_ENV) && terraform init -upgrade -reconfigure \
		-backend-config="$(INFRA_BACKEND)"

init-config:
	$(CHECK_ENV)
	@mkdir -p $(STATE_DIR) $(PLANS_DIR)
	@chmod 700 $(STATE_DIR)
	@$(ENSURE_KUBECONFIG)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && terraform init -upgrade -reconfigure \
		-backend-config="$(CONFIG_BACKEND)"

init: init-infra init-config

plan-infra: init-infra
	$(CHECK_ENV)
	@echo "Planning infra stack (ENV=$(ENV))..."
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform plan -out=../../$(INFRA_PLAN)

plan-config: init-config
	$(CHECK_ENV)
	@echo "Planning config stack (ENV=$(ENV))..."
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform plan -out=../../$(CONFIG_PLAN)

plan: plan-infra plan-config

apply-infra:
	$(CHECK_ENV)
	@if [ ! -f "$(INFRA_PLAN)" ]; then echo "No infra plan — run 'make plan-infra ENV=$(ENV)'"; exit 1; fi
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform apply ../../$(INFRA_PLAN)
	$(PROTECT_STATE)

# Fast path: config changes converge without touching infrastructure.
apply-config: init-config
	$(CHECK_ENV)
	@echo "Applying config stack only (ENV=$(ENV))..."
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform plan -out=../../$(CONFIG_PLAN)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform apply ../../$(CONFIG_PLAN)
	$(PROTECT_STATE)

apply:
	$(CHECK_ENV)
	@if [ ! -f "$(INFRA_PLAN)" ]; then echo "No infra plan — run 'make plan ENV=$(ENV)'"; exit 1; fi
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform apply ../../$(INFRA_PLAN)
	$(PROTECT_STATE)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform plan -out=../../$(CONFIG_PLAN)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform apply ../../$(CONFIG_PLAN)
	$(PROTECT_STATE)

# Plan and apply both stacks in order (config planned AFTER infra applies, so
# it sees the real cluster).
plan-apply: init
	$(CHECK_ENV)
	@echo "Deploying infra stack (ENV=$(ENV))..."
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform plan -out=../../$(INFRA_PLAN)
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform apply ../../$(INFRA_PLAN)
	$(PROTECT_STATE)
	@echo "Deploying config stack (ENV=$(ENV))..."
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform plan -out=../../$(CONFIG_PLAN)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform apply ../../$(CONFIG_PLAN)
	$(PROTECT_STATE)

# --------------------------------------------------------------------------
# Generated secrets
# --------------------------------------------------------------------------

secrets:
	$(CHECK_ENV)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform output -json generated_secrets | jq .

# --------------------------------------------------------------------------
# Destroy
# --------------------------------------------------------------------------

destroy:
	$(CHECK_ENV)
	@echo "WARNING: destroying ALL infrastructure for ENV=$(ENV)!"
	@echo "Press Ctrl+C to cancel, or wait 5 seconds to continue..."
	@sleep 5
	@$(ENSURE_KUBECONFIG)
	@echo "Destroying config stack (best effort)..."
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform destroy -auto-approve -refresh=false || true
	$(PROTECT_STATE)
	@echo "Destroying infra stack..."
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform destroy -auto-approve
	$(PROTECT_STATE)

destroy-fast:
	$(CHECK_ENV)
	@echo "WARNING: fast destroy without refresh (ENV=$(ENV))!"
	@echo "Press Ctrl+C to cancel, or wait 3 seconds to continue..."
	@sleep 3
	@$(ENSURE_KUBECONFIG)
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform destroy -auto-approve -refresh=false || true
	$(PROTECT_STATE)
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform destroy -auto-approve -refresh=false
	$(PROTECT_STATE)

# Removes generated artifacts for ONE environment, never the Terraform state —
# deleting state orphans running VMs and managed clusters.
clean:
	$(CHECK_ENV)
	@echo "Removing generated artifacts for $(ENV) (state is preserved)..."
	@rm -rf $(ARTIFACTS_ROOT)/$(ENV)/kubernetes $(ARTIFACTS_ROOT)/$(ENV)/talos $(ARTIFACTS_ROOT)/$(ENV)/talos-config \
		$(ARTIFACTS_ROOT)/$(ENV)/talos-secrets $(INFRA_PLAN) $(CONFIG_PLAN)
	@echo "Done. Terraform state under $(STATE_DIR)/ was kept."

list:
	$(CHECK_ENV)
	@echo "--- infra stack ---"
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform state list
	@echo "--- config stack ---"
	@cd $(CONFIG_DIR) && $(LOAD_ENV) && $(BIND_CONFIG) && terraform state list

show:
	$(CHECK_ENV)
	@cd $(INFRA_DIR) && $(LOAD_ENV) && $(BIND_INFRA) && terraform show

# --------------------------------------------------------------------------
# Manifest Rendering (Jsonnet -> YAML)
# --------------------------------------------------------------------------

CILIUM_VERSION ?= 1.20.0
CILIUM_MANIFEST := config/manifests/cilium-$(CILIUM_VERSION).yaml

render: render-thanos render-cilium

render-thanos:
	@echo "Rendering Thanos manifests..."
	@cd rendering/thanos && jb install && \
	jsonnet -J vendor -m ../../gitops/tooling-observability/thanos/ thanos.jsonnet && \
	cd ../../gitops/tooling-observability/thanos && \
	for f in thanos-*; do [ -f "$$f" ] && [ "$${f##*.}" != "yaml" ] && yq -p json -o yaml "$$f" > "$$f.yaml" && rm "$$f"; done || true
	@echo "Thanos manifests rendered to gitops/tooling-observability/thanos/"

render-cilium:
	@echo "Rendering Cilium $(CILIUM_VERSION) bootstrap manifest..."
	@mkdir -p config/manifests
	@cat rendering/cilium/namespace.yaml > $(CILIUM_MANIFEST)
	@helm template cilium cilium \
		--repo https://helm.cilium.io/ \
		--version $(CILIUM_VERSION) \
		--namespace cilium \
		-f rendering/cilium/values.yaml \
		>> $(CILIUM_MANIFEST)
	@if grep -q "^kind: Secret" $(CILIUM_MANIFEST); then \
		rm $(CILIUM_MANIFEST); \
		echo "ERROR: rendered manifest contains Secrets — check hubble is disabled"; \
		exit 1; \
	fi
	@echo "Rendered to $(CILIUM_MANIFEST)"

# --------------------------------------------------------------------------
# GitOps OCI Artifact Management
# --------------------------------------------------------------------------

push-gitops:
	$(CHECK_ENV)
	@echo "Pushing gitops artifact to oci://$(OCI_REPO):$(GITOPS_VERSION)..."
	@set -a && source $(ENV_FILE) && set +a && \
	flux push artifact oci://$(OCI_REPO):$(GITOPS_VERSION) \
		--path=./$(GITOPS_DIR) \
		--source="$(shell git config --get remote.origin.url)" \
		--revision="$(shell git rev-parse --short HEAD)" \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD"
	@echo "Pushed oci://$(OCI_REPO):$(GITOPS_VERSION)"

tag-gitops:
	$(CHECK_ENV)
	@if [ -z "$(TAG)" ]; then echo "Usage: make tag-gitops TAG=v1.0.0"; exit 1; fi
	@set -a && source $(ENV_FILE) && set +a && \
	flux tag artifact oci://$(OCI_REPO):$(GITOPS_VERSION) --tag=$(TAG) \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD"
	@echo "Tagged oci://$(OCI_REPO):$(GITOPS_VERSION) as $(TAG)"

release:
	$(CHECK_ENV)
	@if [ -z "$(TAG)" ]; then echo "Usage: make release TAG=v0.3.0 [MSG=\"...\"]"; exit 1; fi
	git tag -a $(TAG) -m "$(or $(MSG),Release $(TAG))"
	git push origin $(TAG)
	@set -a && source $(ENV_FILE) && set +a && \
	flux push artifact oci://$(OCI_REPO):$(TAG) \
		--path=./$(GITOPS_DIR) \
		--source="$(shell git config --get remote.origin.url)" \
		--revision="$(TAG)@sha1:$(shell git rev-parse HEAD)" \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD" && \
	flux tag artifact oci://$(OCI_REPO):$(TAG) --tag=latest \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD"
	@echo "Released $(TAG)"

list-artifacts:
	$(CHECK_ENV)
	@set -a && source $(ENV_FILE) && set +a && \
	flux list artifacts oci://$(OCI_REPO) \
		--creds="$$OCI_REPO_USERNAME:$$OCI_REPO_PASSWORD"

# --------------------------------------------------------------------------
# Performance testing (perf/)
#
# Config lives with the environment it belongs to and is gitignored by the
# same rule as config.yaml:
#   <environments-root>/<ENV>/perf-topology.yaml
#   <environments-root>/<ENV>/perf-scenarios/<SCENARIO>.yaml
# Results are committed, under perf-result/<ENV>/<SCENARIO>/<timestamp>/.
# ENV is required by every target.
#
# Scenario values are overridable as make variables (TPS=, DURATION=, ...);
# every override is recorded in the run's scenario-snapshot.yaml, so a result
# is reproducible from its report rather than from the shell history.
# --------------------------------------------------------------------------
.PHONY: perf-seed perf-check perf-run perf-index

# NOTE: deliberately NOT $(CHECK_ENV). That guard requires
# <environments-root>/<ENV>/config.yaml, which would tie perf to the Terraform
# environment layout. A topology name need not be a Terraform environment,
# and adopters may have neither. The scripts validate the topology instead.
define CHECK_PERF_ENV
	@if [ -z "$(ENV)" ]; then \
		echo "Usage: make $@ ENV=<name>   (reads $(ENVIRONMENTS_ROOT)/<name>/perf-topology.yaml)"; \
		echo "Environments with a perf topology: $$(for d in environments/*/; do [ -f "$$d/perf-topology.yaml" ] && basename $$d; done | tr '\n' ' ')"; \
		exit 1; \
	fi
endef

perf-seed:
	$(CHECK_PERF_ENV)
	@ENV=$(ENV) perf/bin/seed.sh

perf-check:
	$(CHECK_PERF_ENV)
	@ENV=$(ENV) perf/bin/check.sh

perf-run:
	$(CHECK_PERF_ENV)
	@if [ -z "$(SCENARIO)" ]; then \
		echo "Usage: make perf-run ENV=<env> SCENARIO=<name> [TPS=.. DURATION=..]"; \
		echo "Available for $(ENV): $$(ls -1 $(ENV_DIR)/perf-scenarios 2>/dev/null | sed 's/\.yaml$$//' | tr '\n' ' ')"; \
		exit 1; \
	fi
	@ENV=$(ENV) perf/bin/run.sh

perf-index:
	@perf/bin/index.sh
