apiVersion: v1
kind: Service
metadata:
  name: keto-metrics
  namespace: ory
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4468"
    prometheus.io/path: "/metrics/prometheus"
spec:
  selector:
    app.kubernetes.io/name: keto
    app.kubernetes.io/instance: ory-keto
  ports:
    - name: metrics
      port: 4468
      targetPort: 4468
      protocol: TCP
