apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hydra-secret
  namespace: ory
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: hydra-secret
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: secret/hydra
        property: dsn
    - secretKey: secretsSystem
      remoteRef:
        key: secret/hydra
        property: secretsSystem
    - secretKey: secretsCookie
      remoteRef:
        key: secret/hydra
        property: secretsCookie
