apiVersion: v1
kind: Namespace
metadata:
  name: env-system
  labels:
    app.kubernetes.io/part-of: mojaloop
    mojaloop.io/layer: environment
---
apiVersion: v1
kind: Namespace
metadata:
  name: mojaloop
  labels:
    app.kubernetes.io/part-of: mojaloop
    mojaloop.io/layer: environment
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    app.kubernetes.io/part-of: mojaloop
    mojaloop.io/layer: environment
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    app.kubernetes.io/part-of: mojaloop
    mojaloop.io/layer: environment
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/part-of: mojaloop
    mojaloop.io/layer: environment
---
apiVersion: v1
kind: Namespace
metadata:
  name: ory
  labels:
    app.kubernetes.io/part-of: mojaloop
    mojaloop.io/layer: environment
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcm
  labels:
    app.kubernetes.io/part-of: mojaloop
    mojaloop.io/layer: environment
