apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 12h
  targetNamespace: external-secrets
  install:
    crds: Create
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-values-override
      valuesKey: values.yaml
      optional: true
  values:
    webhook:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 256Mi
  dependsOn:
    - name: cert-manager
