apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway/gateway.yaml
  - gateway/gateway-ext.yaml
  - flux-httproute.yaml
  - flux-networkpolicy.yaml
  - goldilocks-httproute.yaml
