# ReferenceGrants allowing HTTPRoutes to reference the shared Gateway in platform-system
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-ref
  namespace: platform-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: vault
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: ory
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: mcm
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: mojaloop
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: finance-portal
  to:
    - group: gateway.networking.k8s.io
      kind: Gateway
