cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
  extraManifests:
    - "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.4.0/experimental-install.yaml"
    - "https://raw.githubusercontent.com/mojaloop/ml-deployment-toolkit/main/config/manifests/cilium-1.20.0.yaml"
machine:
  features:
    hostDNS:
      enabled: true
      forwardKubeDNSToHost: false # Cilium + Talos GitHub issue #35153
