apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-ui-authzdocument.yaml
  - goldilocks-ui-authzdocument.yaml
  - hubble-ui-authzdocument.yaml
  - intapi-authzdocument.yaml
