apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kratos-selfservice-ui
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kratos-selfservice-ui-node
      version: "0.62.1"
      sourceRef:
        kind: HelmRepository
        name: ory
      interval: 12h
  targetNamespace: ory
  install:
    createNamespace: false
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
      strategy: uninstall
  dependsOn:
    - name: kratos
  valuesFrom:
    - kind: ConfigMap
      name: kratos-selfservice-ui-values-override
      valuesKey: values.yaml
      optional: true
  values:
    fullnameOverride: "kratos-ui"

    secret:
      enabled: false
      nameOverride: kratos-secret

    config:
      csrfCookieName: "__HOST-auth.int.${domain}-x-csrf-token"

    kratosAdminUrl: "http://kratos-admin"
    kratosPublicUrl: "http://kratos-public"
    kratosBrowserUrl: "https://auth.int.${domain}/kratos"

    jwksUrl: "http://oathkeeper-api"

    projectName: "SecureApp"
