apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: reporting-events-db-secret
  namespace: mojaloop
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: reporting-events-db-secret
    creationPolicy: Owner
  data:
    - secretKey: mongodb-password
      remoteRef:
        key: secret/finance-portal
        property: mongodb_app_password
