apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: role-assign-svc-secret
  namespace: mojaloop
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: role-assign-svc-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: secret/finance-portal
        property: role_assign_svc_secret
