apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-credentials
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: harbor-credentials
    creationPolicy: Owner
  data:
    - secretKey: adminPassword
      remoteRef:
        key: secret/data/harbor
        property: adminPassword
