apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: harbor-admin
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/harbor
        property: adminPassword
