# Kafka topics for bulk transfer processing.
# Created by Strimzi entity operator (topicOperator: {} in Kafka CR).
# These are required when mojaloop-bulk is enabled in the Mojaloop HelmRelease.
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: topic-bulk-prepare
  namespace: data
  labels:
    strimzi.io/cluster: mojaloop-kafka
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 2
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: topic-bulk-fulfil
  namespace: data
  labels:
    strimzi.io/cluster: mojaloop-kafka
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 2
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: topic-bulk-processing
  namespace: data
  labels:
    strimzi.io/cluster: mojaloop-kafka
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 2
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: topic-bulk-get
  namespace: data
  labels:
    strimzi.io/cluster: mojaloop-kafka
spec:
  partitions: 1
  replicas: 3
  config:
    min.insync.replicas: 2
