apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kafka-metrics-configmap.yaml
  - kafka-metrics-service.yaml
  - kafka-exporter-metrics-service.yaml
  - kafka.yaml
  - kafka-topics.yaml
