apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fairwinds-stable
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.fairwinds.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vpa
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: vpa
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
      interval: 12h
  targetNamespace: vpa
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: vpa-values-override
      valuesKey: values.yaml
      optional: true
  values:
    recommender:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 100Mi
        limits:
          memory: 256Mi
    updater:
      enabled: false
    admissionController:
      enabled: false
