apiVersion: v1
kind: Service
metadata:
  name: mojaloop-kafka-exporter-metrics
  namespace: data
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9404"
    prometheus.io/path: "/metrics"
spec:
  clusterIP: None
  selector:
    strimzi.io/cluster: mojaloop-kafka
    strimzi.io/component-type: kafka-exporter
  ports:
    - name: metrics
      port: 9404
      targetPort: 9404
      protocol: TCP
