apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway-api/crds.yaml
  - cilium/helmrelease.yaml
  - lb-ipam/lb-ipam.yaml
  - openebs/helmrelease.yaml
  - hubble-httproute.yaml
