apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-s3-credentials
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: tempo-s3-credentials
    creationPolicy: Owner
  data:
    - secretKey: accessKey
      remoteRef:
        key: secret/data/minio
        property: rootUser
    - secretKey: secretKey
      remoteRef:
        key: secret/data/minio
        property: rootPassword
