apiVersion: v1
kind: Secret
metadata:
  name: dns-provider-credentials
  namespace: cert-manager
type: Opaque
stringData:
  access-token: "${DIGITALOCEAN_TOKEN}"
---
apiVersion: v1
kind: Secret
metadata:
  name: dns-provider-credentials
  namespace: external-dns
type: Opaque
stringData:
  access-token: "${DIGITALOCEAN_TOKEN}"
