apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos-objstore-config
  namespace: observability
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: thanos-objstore-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        objstore.yml: |
          type: S3
          config:
            bucket: thanos
            endpoint: minio.minio:9000
            insecure: true
            access_key: "{{ .accessKey }}"
            secret_key: "{{ .secretKey }}"
  data:
    - secretKey: accessKey
      remoteRef:
        key: secret/data/minio
        property: rootUser
    - secretKey: secretKey
      remoteRef:
        key: secret/data/minio
        property: rootPassword
