apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kratos-secret
  namespace: ory
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: kratos-secret
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: secret/kratos
        property: dsn
    - secretKey: secretsCipher
      remoteRef:
        key: secret/kratos
        property: secretsCipher
    - secretKey: secretsCookie
      remoteRef:
        key: secret/kratos
        property: secretsCookie
    - secretKey: secretsCSRFCookie
      remoteRef:
        key: secret/kratos
        property: secretsCSRFCookie
    - secretKey: secretsDefault
      remoteRef:
        key: secret/kratos
        property: secretsDefault
    - secretKey: smtpConnectionURI
      remoteRef:
        key: secret/kratos
        property: smtpConnectionURI
