apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keto-secret
  namespace: ory
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: keto-secret
    creationPolicy: Owner
  data:
    - secretKey: dsn
      remoteRef:
        key: secret/keto
        property: dsn
