#!/usr/bin/env bash
# Usage: generate-backend.sh <env> <stack> [<state-dir>]
#   <stack> = infra | config
#
# Engine-generated per-environment Terraform state backend (design doc §2 L3:
# backend blocks cannot interpolate, so the engine writes them). Reads
# <ENVIRONMENTS_ROOT>/<env>/state-backend.yaml (absent = local, the historical
# layout) and:
#   1. writes <state-dir>/backend-<stack>.hcl — the full -backend-config
#      payload for `terraform init` (0600: it carries STATE_S3_* credentials
#      from .env when the backend is s3)
#   2. writes or REMOVES src/<stack>/backend_s3_override.tf — the override
#      that switches the stack's backend type from the base `local` to `s3`
#      (gitignored via *_override.tf; regenerated on every bind because the
#      stack directories are shared by every environment)
#
# Every Makefile target that runs terraform binds through this generator, so
# the backend always matches the CURRENT env — never whichever one was
# initialized last.
#
# SWITCHING an existing environment to s3 does NOT move its state: run
# tools/migrate-state-backend.sh (operator action, never automatic).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENVIRONMENTS_ROOT="${ENVIRONMENTS_ROOT:-../environments}"
ARTIFACTS_ROOT="${ARTIFACTS_ROOT:-../artifacts}"

ENV="${1:-}"
STACK="${2:-}"
STATE_DIR="${3:-$ARTIFACTS_ROOT/$ENV/state}"
if [ -z "$ENV" ] || { [ "$STACK" != "infra" ] && [ "$STACK" != "config" ]; }; then
  echo "usage: $0 <env> infra|config [<state-dir>]" >&2
  exit 2
fi
ENV_DIR="$ENVIRONMENTS_ROOT/$ENV"
[ -f "$ENV_DIR/config.yaml" ] || { echo "error: $ENV_DIR/config.yaml not found" >&2; exit 2; }

SB="$ENV_DIR/state-backend.yaml"
STACK_DIR="src/$STACK"
OVERRIDE="$STACK_DIR/backend_s3_override.tf"
mkdir -p "$STATE_DIR"
chmod 700 "$STATE_DIR" 2>/dev/null || true
OUT="$STATE_DIR/backend-$STACK.hcl"

btype="local"
if [ -f "$SB" ]; then
  yq -o json e '.' "$SB" | python3 tools/validate.py config/schemas/state-backend.schema.json
  btype=$(yq eval '.type' "$SB")
fi

abs_state_dir="$(cd "$STATE_DIR" && pwd)"

if [ "$btype" = "local" ]; then
  rm -f "$OVERRIDE"
  umask 077
  printf 'path = "%s/%s.tfstate"\n' "$abs_state_dir" "$STACK" > "$OUT"
  echo "backend($ENV/$STACK): local -> $abs_state_dir/$STACK.tfstate"
  exit 0
fi

# --- s3 ---------------------------------------------------------------------
endpoint=$(yq eval '.s3.endpoint // ""' "$SB")
bucket=$(yq eval '.s3.bucket' "$SB")
region=$(yq eval '.s3.region' "$SB")
key_prefix=$(yq eval ".s3.key_prefix // \"$ENV\"" "$SB")
use_lockfile=$(yq eval '.s3.use_lockfile // true' "$SB")

# Credentials are operator-plane secrets from .env, never from this file.
access_key="${STATE_S3_ACCESS_KEY:-}"
secret_key="${STATE_S3_SECRET_KEY:-}"
if { [ -z "$access_key" ] || [ -z "$secret_key" ]; } && [ -f "$ENV_DIR/.env" ]; then
  access_key=$(sed -n 's/^ *STATE_S3_ACCESS_KEY=//p' "$ENV_DIR/.env" | tail -1 | tr -d '"')
  secret_key=$(sed -n 's/^ *STATE_S3_SECRET_KEY=//p' "$ENV_DIR/.env" | tail -1 | tr -d '"')
fi
if [ -z "$access_key" ] || [ -z "$secret_key" ]; then
  echo "error: state-backend.yaml declares type s3 but STATE_S3_ACCESS_KEY / STATE_S3_SECRET_KEY are not set in $ENV_DIR/.env — state credentials are stated, never derived." >&2
  exit 1
fi

# Backend type override: replaces the base `backend "local"` block
# (Terraform override-file semantics). Content is static; config arrives via
# -backend-config so nothing secret lands in the stack directory.
printf '%s\n' \
  '# GENERATED by tools/generate-backend.sh — DO NOT EDIT, DO NOT COMMIT' \
  '# (gitignored via *_override.tf). Selects the s3 backend for the current' \
  '# environment; the actual config is passed via -backend-config.' \
  'terraform {' \
  '  backend "s3" {}' \
  '}' > "$OVERRIDE"

umask 077
{
  echo "# GENERATED by tools/generate-backend.sh for env $ENV, stack $STACK — contains credentials, mode 0600"
  echo "bucket = \"$bucket\""
  echo "key    = \"$key_prefix/$STACK.tfstate\""
  echo "region = \"$region\""
  echo "access_key = \"$access_key\""
  echo "secret_key = \"$secret_key\""
  echo "use_lockfile = $use_lockfile"
  if [ -z "$endpoint" ]; then
    # Real AWS S3: request server-side encryption for the state objects.
    # (Not set for custom endpoints — a MinIO without KMS rejects SSE
    # headers; there transport TLS + a private bucket is the model, and
    # client-side encryption is not something the s3 backend offers.)
    echo "encrypt      = true"
  else
    # S3-compatible (MinIO): path-style addressing, skip AWS-only validations.
    echo "endpoints = { s3 = \"$endpoint\" }"
    echo "use_path_style              = true"
    echo "skip_credentials_validation = true"
    echo "skip_region_validation      = true"
    echo "skip_requesting_account_id  = true"
    echo "skip_metadata_api_check     = true"
    echo "skip_s3_checksum            = true"
  fi
} > "$OUT"
echo "backend($ENV/$STACK): s3 -> ${endpoint:-aws} bucket=$bucket key=$key_prefix/$STACK.tfstate lockfile=$use_lockfile"
